CREATE TABLE IF NOT EXISTS proyecto(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    emprendedor integer,
    nombre text NOT NULL,
    objetivos text,
    descripcion text NOT NULL,
    compromiso_social text NOT NULL,
    image text NOT NULL,
    videos text NOT NULL,
    costo_minimo bigint NOT NULL,
    costo_optimo bigint NOT NULL,
    calificacion integer DEFAULT 0,
    fecha date,
    estado boolean DEFAULT false,
    ubicacion text NOT NULL
)